### ISSUE TITLE
Vue du profil

### ISSUE THREAD

**Issue by rossmat** [HE-Arc/SocialEvents#12]
> Evénements publiés par la personne
> Possibilité d'importer + statut "import en cours"
> Possibilité de masquer un événement
> ...?

**Comment by kamyh** [comment]
Je pense que masquer sert pas vraiment. si tu veut pas d'un event tu le supprime

**Comment by rossmat** [comment]
Le masquage met le flag is_published à false. L'événement n'est plus listé, mais pas non plus réimporté tant qu'il est dans la base de données.

A faire encore : 
* Texte de contenu concernant le fetching
* Possibilité de spécifier le mot recherché lors du fetching
* Bouton supprimer tout ?
* Intégrer scroll infini ?

**Comment by rossmat** [comment]
Design par @MichaelCaraccio 
Voir pour les fonctionnalités ci-dessus!

**Comment by rossmat** [comment]
Fait : 
* Evénements publiés par la personne
* Possibilité d'importer + statut "import en cours"
* Possibilité de masquer un événement
* Texte de contenu concernant le fetching

A voir si utile : 
* Possibilité de spécifier le mot recherché lors du fetching ?
* Bouton supprimer tout ?
* Intégrer scroll infini ?

**Comment by rossmat** [comment]
Updated
