### ISSUE TITLE
Seeds et déploiement : bug version ruby en production

### ISSUE THREAD

**Issue by rossmat** [HE-Arc/SocialEvents#15]
Nécessite de modifier le format des seeds au niveau des DateTime

En relation avec https://bugs.ruby-lang.org/issues/10758

**Comment by kamyh** [comment]
Format modifier ('2007-02-01 15:30:45').
A tester sur le server de deploiement

**Comment by rossmat** [comment]
Corrigé en forçant les dates avec 
```
DateTime.strptime("2015-03-26 15:30:45", "%Y-%m-%d %H:%M:%S")
```
