### ISSUE TITLE
Surcharge de chargement de fichiers JS

### ISSUE THREAD

**Issue by rossmat** [HE-Arc/SocialEvents#16]
Avec tous les fichiers Javascript on a ~50-60 requêtes sur l'accueil, et >100 requêtes sur la page avec Google Maps. Au moins 30 requêtes sont inutiles sur l'accueil, à cause de GMaps. Est-ce que tous les fichiers javascripts/gmaps/* sont nécessaires ?

Il faut réfléchir à limiter les chargements automatiques de Rails... 
* Charger uniquement le fichier JS du contrôleur actuel ?
* Limiter le chargement automatique des directives de application.js au dossier racine, sans récursion dans le dossier gmaps ?
* Charger la librairie gmaps que lorsqu'on utilise, dans /events/id ? Auquel cas, on ne peut injecter les scripts JS dans le "head" du template à cause de turbolinks... Où faire ce chargement conditionnel ?
* Faire des directives application.js suivant la page courante ? Même problème avec turbolinks ?
* ...

**Comment by kamyh** [comment]
Solution trouvée.
Les .js a charger sur tous le site vont dans le dossier /assets/javascripts/global

**Comment by kamyh** [comment]
data-turbolinks-track="true" TRES IMPORTANT

**Comment by MichaelCaraccio** [comment]
Ah cool! Et à quoi sert le data-turbolinks-track="true" ?

**Comment by kamyh** [comment]
EN gros a mettre le chargement du js cible dans la loop de turbocassecouilles

**Comment by MichaelCaraccio** [comment]
Sympa
