### ISSUE TITLE
Fixes/improvement

### ISSUE THREAD

**Issue by kamyh** [HE-Arc/SocialEvents#19]
- Monter calendrier
- pages "no result found to your research"

**Comment by rossmat** [comment]
- Largeur 100% page : map, cover
- Image cliquable cover

**Comment by rossmat** [comment]
Voir mises à jour ;)

**Comment by rossmat** [comment]
![image](https://cloud.githubusercontent.com/assets/7804733/6760798/8b551ddc-cf4c-11e4-83da-2bede0626345.png)

Désolé ma localisation est vers Berne... :fu:

**Comment by rossmat** [comment]
En mode "responsive design mobile", il faudrait ajouter le calendrier désormais car on liste pour le jour courant saisi dans le calendrier.
