### ISSUE TITLE
img

### ISSUE THREAD

**Issue by kamyh** [HE-Arc/SocialEvents#26]
default images

**Comment by kamyh** [comment]
Du coup on gere les image par default en cas de cover inexistante comment ?
Lors de l'importation ou lors de l'affichage ?

**Comment by rossmat** [comment]
C'est géré lors de l'importation pour une cover par défaut normalement. J'ai encore eu une cover vide récemment après avoir fait le code, mais j'ai pas encore regardé pour savoir si c'est une erreur de code (range de random) ou si c'était un vieux seed sans image.
