### ISSUE TITLE
Ajout configuration de l'application dans le readme

### ISSUE THREAD

**Issue by toxis** [HE-Arc/SocialEvents#43]
Éventuellement ajouter dans le readme comment configurer votre application et les dépendances.
- Nécessite une application Facebook
- Configuration de l'app id/app secret dans l'application Rails
- Autorisations particulières?
- Configuration personnalisée de delayed_job

J'ai testé sur srvz-isic04 ça a l'air de fonctionner même si je ne sais pas d'où viennent tous les événements qui sont importés ^^. Par contre je n'ai pas réussi à faire fonctionner correctement sur ma machine de dev avec une de mes applis Facebook.

Il semble que c'est le delayed_job qui pose des problèmes. Si je force en synchrone, c'est bon. Y a-t-il quelque chose de particulier à configurer avec delayed_job?

**Comment by rossmat** [comment]
README mis à jour pour application Facebook et delayed_jobs.
