### ISSUE TITLE
Récupération de la position GPS de l'utilisateur

### ISSUE THREAD

**Issue by MichaelCaraccio** [HE-Arc/SocialEvents#6]

**Comment by kamyh** [comment]
Si cest uniquement pour afficher sur la map je m'en chargerai

**Comment by MichaelCaraccio** [comment]
Pas seulement, j'utilise la position de l'utilisateur pour pouvoir récupérer les lieux intéressants autour de l'utilisateur (bar, musée, théâtre, etc).

**Comment by toxis** [comment]
Bonjour,

Je ne sais pas exactement ce que vous souhaitez développer comme fonctionnaltié mais je me permets d'intervenir pour vous fournir 2 screencasts qui peuvent être intéressants sur la géolocalisation et la possibilité de faire des requêtes spatiales avec Rails:

* https://www.codeschool.com/screencasts/groupon-geolocation
* https://www.codeschool.com/screencasts/groupon-spatial-queries

En espérant que cela puisse vous aider et vous donner aussi des idées ;-)

**Comment by MichaelCaraccio** [comment]
Merci pour les liens!
